language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    - os: linux
      env:
    - os: osx
      env:
    - os: windows
      env:
    - os: linux
      env:
        - TARGET=wasm32-unknown-unknown
    - os: linux
      env:
        - TARGET=wasm32-unknown-emscripten

before_script: |
  if [[ -n "$TARGET" ]]; then
    rustup target add $TARGET
  fi
  if [[ "$TRAVIS_RUST_VERSION" == nightly && "$TRAVIS_OS_NAME" == "linux" ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

script:
  - |
    if [[ -n "$TARGET" ]]; then
      cargo build --target $TARGET --verbose --all
    else
      cargo build --verbose --all
    fi
  - |
    if [[ -z "$TARGET" ]]; then
      cargo test --verbose --all
    fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
