language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  include:
    - os: linux
      env: TARGET=wasm32-unknown-unknown
      rust: stable
    - os: linux
      env: TARGET=wasm32-unknown-unknown
      rust: beta
    - os: linux
      env: TARGET=wasm32-unknown-unknown
      rust: nightly
    - os: linux
      env: TARGET=wasm32-unknown-emscripten
      rust: stable
    - os: linux
      env: TARGET=wasm32-unknown-emscripten
      rust: beta
    - os: linux
      env: TARGET=wasm32-unknown-emscripten
      rust: nightly

before_script: |
  if [[ -n "$TARGET" ]]; then
    rustup target add $TARGET
  fi
  if [[ "$TRAVIS_RUST_VERSION" == nightly && "$TRAVIS_OS_NAME" == "linux" ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

script:
  - |
    if [[ -n "$TARGET" ]]; then
      cargo build --target $TARGET --verbose --all
    else
      cargo build --verbose --all
    fi
  - |
    if [[ -z "$TARGET" ]]; then
      cargo test --verbose --all
    fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
