name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build ${{ matrix.target }} ${{ matrix.rust }} (on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, nightly]

    steps:
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v4
      - run: cargo install cargo-tarpaulin
      - run: cargo build --all
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test --all
      - run: |
          cargo tarpaulin --out Xml
          bash <(curl -s https://codecov.io/bash)
        if: matrix.os == 'ubuntu-latest' && matrix.rust == 'nightly' && matrix.target == 'native'
